import { GoogleGenAI } from "@google/genai";

export const config = {
  maxDuration: 60,
};

export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { userImageBase64, styleImageBase64 } = req.body;

  if (!userImageBase64 || !styleImageBase64) {
    return res.status(400).json({ error: 'Missing image data' });
  }

  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey) {
    return res.status(500).json({ error: 'GEMINI_API_KEY not configured on server' });
  }

  try {
    const ai = new GoogleGenAI({ apiKey });
    const model = "gemini-2.0-flash-exp-image-generation";
    const prompt = "Digital Makeup Transfer. Apply the reference style to the source face. Preserve identity.";

    const cleanUser = userImageBase64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, "");
    const cleanStyle = styleImageBase64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, "");

    const response = await ai.models.generateContent({
      model,
      contents: {
        parts: [
          { text: prompt },
          { inlineData: { mimeType: 'image/jpeg', data: cleanUser } },
          { inlineData: { mimeType: 'image/jpeg', data: cleanStyle } }
        ]
      }
    });

    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return res.status(200).json({ image: `data:image/png;base64,${part.inlineData.data}` });
        }
      }
    }
    
    return res.status(500).json({ error: "No image generated by the model." });
  } catch (error: any) {
    console.error("Image Generation API failed:", error);
    return res.status(500).json({ error: error.message || 'Internal Server Error' });
  }
}
